#!/usr/bin/bash

BASE_DIR=$(dirname $0)
LIB_DIR="${BASE_DIR}/lib"
if [ ! -d "${LIB_DIR}/venv" ]
then
  pushd ${LIB_DIR} 1>/dev/null
  python3 -m venv ./venv &>/dev/null
  source ./venv/bin/activate
  pip3 install flask &>/dev/null
  popd 1>/dev/null
fi

${LIB_DIR}/venv/bin/python3 ${LIB_DIR}/main.py
