#!/usr/bin/bash

PYTHON="python3.11"

BASE_DIR=$(dirname $0)
LIB_DIR="${BASE_DIR}/lib"
if [ ! -d "${LIB_DIR}/venv" ]
then
  pushd ${LIB_DIR} 1>/dev/null
  ${PYTHON} -m venv ./venv &>/dev/null
  source ./venv/bin/activate
  python3 -m pip install flask &>/dev/null
  popd 1>/dev/null
fi

${LIB_DIR}/venv/bin/python3 ${LIB_DIR}/cli.py $@
