#!/bin/bash
#
function help() {
  cat << EOF

  Cosmpdrome project stage 1
  The script should be called but slurm spank plugin stage 0
  The script should verify that all the calls works correctly and output is logged.

  Usage: ${SCRIPTNAME} --context <CONTEXT> --function <FUNCTION> --payload <EDF>

  Options:

  --context : specify slurm context
  
  --function : specify slurm function

  --payload : specify EDF filepath

EOF
}

function log() {
  MSG="$@"
  echo "stage1-v${VERSION} - $MSG"
  TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S.%3N)
  echo "[${TIMESTAMP}] stage1-v${VERSION} - $MSG" >>${LOG_FILE}
}

function errlog() {
  MSG="$@"
  echo "stage1-v${VERSION} - ERROR: $MSG" >&2
  TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S.%3N)
  echo "[${TIMESTAMP}] stage1-v${VERSION} - ERROR: $MSG" >>${LOG_FILE}
}

function parse_args() {

  while [ -n $1 ] && [ "$1" != "" ]
  do
    case $1 in
      --context)
        shift 1
	SPANK_CONTEXT=${1}
        shift 1
        ;;
      --function)
        shift 1
	SPANK_FUNCTION=${1}
        shift 1
        ;;
      --payload)
        shift 1
	SPANK_PAYLOAD=${1}
        shift 1
        ;;
      *)
        shift 1
        ;;
    esac
  done

}

function check_environment() {
  set -e
  [ -z "${SPANK_CONTEXT}" ] && \
	  #echo "ERROR(stage1): Missing --context" >&2 && \
	  errlog "Missing --context" && \
	  exit 1

  [ -z "${SPANK_FUNCTION}" ] && \
	  #echo "ERROR(stage1): Missing --function" >&2 && \
	  errlog "Missing --function" && \
	  exit 1

  set +e
}

function execute() {
  if [ -z "${SPANK_PAYLOAD}" ]
  then
    log "Executed: Context ${SPANK_CONTEXT} - Function ${SPANK_FUNCTION}"
  else	  
    log "Executed: Context ${SPANK_CONTEXT} - Function ${SPANK_FUNCTION} - PAYLOAD ${SPANK_PAYLOAD}"
  fi
  #echo "stage1-v${VERSION} - Context ${SPANK_CONTEXT} - Function ${SPANK_FUNCTION} - PAYLOAD ${SPANK_PAYLOAD} - EXECUTED"
  #TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S.%3N)
  #echo "[${TIMESTAMP}] stage1-v${VERSION} - Context ${SPANK_CONTEXT} - Function ${SPANK_FUNCTION} - PAYLOAD ${SPANK_PAYLOAD} - EXECUTED" >>${LOG_FILE}
}

VERSION='0.1a'
NODENAME="${HOSTNAME}"
if [ -n "${SLURM_STAGE0_LOGDIR}" ]
then
  LOG_DIR="${SLURM_STAGE0_LOGDIR}/${NODENAME}" 
else
  LOG_DIR="${HOME}/cosmodrome/${NODENAME}" 
fi
LOG_FILE="${LOG_DIR}/stage1.log"
SCRIPT_DIR="$(readlink -f $(dirname $0))"
SCRIPT_NAME="$(basename $0)"
SCRIPT_ARGS="$@"

[ ! -d ${LOG_DIR} ] && mkdir -p ${LOG_DIR}
log "Executing: ${SCRIPT_DIR}/${SCRIPT_NAME} ${SCRIPT_ARGS}"
parse_args $@
check_environment 
execute
exit 0
