#!/bin/bash
#
function help() {
  cat << EOF

  Slurm Oddity project stage 1
  The script should be called but slurm spank plugin stage 0
  The script should verify that all the calls works correctly and output is logged.

  Usage: ${SCRIPTNAME} --context <CONTEXT> --function <FUNCTION> --payload <EDF>

  Options:

  --context : specify slurm context
  
  --function : specify slurm function

  --payload : specify EDF filepath

EOF
}

function log() {
  MSG="$@"
  echo "stage1-v${VERSION} - $MSG"
  TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S.%3N)
  echo "[${TIMESTAMP}] stage1-v${VERSION} - $MSG" >>${LOG_FILE}
}

function errlog() {
  MSG="$@"
  echo "stage1-v${VERSION} - ERROR: $MSG" >&2
  TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S.%3N)
  echo "[${TIMESTAMP}] stage1-v${VERSION} - ERROR: $MSG" >>${LOG_FILE}
}

function parse_args() {

  while [ -n $1 ] && [ "$1" != "" ]
  do
    case $1 in
      --context)
        shift 1
	SPANK_CONTEXT=${1}
        shift 1
        ;;
      --function)
        shift 1
	SPANK_FUNCTION=${1}
        shift 1
        ;;
      --payload)
        shift 1
	SPANK_PAYLOAD=${1}
        shift 1
        ;;
      *)
        shift 1
        ;;
    esac
  done

}

function check_environment() {
  set -e
  [ -z "${SPANK_CONTEXT}" ] && \
	  #echo "ERROR(stage1): Missing --context" >&2 && \
	  errlog "Missing --context" && \
	  exit 1

  [ -z "${SPANK_FUNCTION}" ] && \
	  #echo "ERROR(stage1): Missing --function" >&2 && \
	  errlog "Missing --function" && \
	  exit 1

  set +e
}

function execute() {
  #if [ "${SPANK_FUNCTION}" == "init" ] && [ "${SPANK_CONTEXT}" == "remote" ]
  #then
  #  ENV_SLURM_OUT=$(env | grep -E '^SLURM|^STIKAZZI')
  #  log "ID_OUT: $(id)"	  
  #  log "HOME: ${HOME}"	  
  #  log "USER: ${USER}"	  
  #  log "PATH: ${PATH}"	  
  #  log "PWD: $(pwd)"
  #  echo "${ENV_SLURM_OUT}" | while read line
  #  do
  #    log "${line}"
  #  done   
  #fi 
  if [ -z "${SPANK_PAYLOAD}" ]
  then
    log "Executed  as \"${EXE_USER}\" : Context ${SPANK_CONTEXT} - Function ${SPANK_FUNCTION}"
  else
    log "Executed  as \"${EXE_USER}\" : Context ${SPANK_CONTEXT} - Function ${SPANK_FUNCTION} - Payload ${SPANK_PAYLOAD}"
  fi
}

VERSION='0.1a'
NODENAME="${HOSTNAME}"

if [ -n "${SLURM_STAGE0_LOGDIR}" ]
then
  LOG_DIR="${SLURM_STAGE0_LOGDIR}/${NODENAME}" 
else
  LOG_DIR="${HOME}/slurm-oddity/${NODENAME}" 
fi

LOG_FILE="${LOG_DIR}/stage1.log"
SCRIPT_DIR="$(readlink -f $(dirname $0))"
SCRIPT_NAME="$(basename $0)"
SCRIPT_ARGS="$@"
EXE_USER=$(id -un)

[ ! -d ${LOG_DIR} ] && mkdir -p ${LOG_DIR}
log "Executing as \"${EXE_USER}\" : ${SCRIPT_DIR}/${SCRIPT_NAME} ${SCRIPT_ARGS}"
parse_args $@
check_environment 
execute
exit 0
